"""Generate `oas.kicad_dru` — JLCPCB-tuned custom KiCad design rules.

KiCad 8/9/10 reads a `.kicad_dru` file with the same basename as the
`.kicad_pcb` automatically. The DRC engine evaluates these alongside the
basic rules embedded in `oas.kicad_pro::board.design_settings.rules`.
They cover per-element-type constraints (track vs via vs pad vs NPTH)
that the basic schema can't express.

Source: rules adapted from third_party/kicad-jlcpcb-dru
(tinfever/KiCAD-Custom-DRC-Rules-for-JLCPCB-with-Unit-Tests). The
upstream targets KiCad 7 but the DRU syntax has been stable since v7.
Verified manually against KiCad 10 documentation.

OAS profile: 2-layer, 1oz copper, standard JLCPCB (no special service).
That maps to track width / clearance min 0.127 mm, via 0.5 mm / 0.3 mm,
edge clearance 0.3 mm. Default OAS routing uses 0.25 mm tracks (well
above the minimum); these rules catch any future regression below the
JLCPCB-acceptable floor.
"""
from __future__ import annotations


def gen_kicad_dru() -> str:
    """Return the full content of `oas.kicad_dru`.

    Header is a generated banner; body is the adapted rule set. Function
    is pure-Python with no I/O — caller writes to disk.
    """
    rules = [
        "(version 1)",
        "# AUTO-GENERATED by boardgen/14_design_rules.py — do NOT hand-edit.",
        "# Source: third_party/kicad-jlcpcb-dru (tinfever, adapted).",
        "# Profile: JLCPCB 2-layer, 1oz copper, standard service.",
        "",
        "# --- Minimum trace width and clearance (2-layer, 1oz) ---",
        '(rule "Minimum Trace Width and Spacing"',
        "\t(constraint track_width (min 0.127mm))",
        "\t(constraint clearance (min 0.127mm))",
        "\t(condition \"A.Type == 'track'\"))",
        "",
        "# --- Drill / hole size (mechanical NPTH range) ---",
        '(rule "drill hole size (mechanical)"',
        "\t(constraint hole_size (min 0.15mm) (max 6.3mm)))",
        "",
        "# --- Via diameter and hole size (2-layer standard) ---",
        '(rule "Minimum Via Diameter and Hole Size"',
        "\t(constraint hole_size (min 0.3mm))",
        "\t(constraint via_diameter (min 0.5mm))",
        "\t(constraint disallow buried_via)",
        "\t(condition \"A.Type == 'via'\"))",
        "",
        "# --- PTH and NPTH pad size ---",
        '(rule "PTH Hole Size"',
        "\t(constraint hole_size (min 0.2mm) (max 6.35mm))",
        "\t(condition \"A.Type != 'Via' && A.isPlated()\"))",
        "",
        '(rule "Minimum Non-plated Hole Size"',
        "\t(constraint hole_size (min 0.5mm))",
        "\t(condition \"A.Type == 'pad' && !A.isPlated()\"))",
        "",
        "# Pad Size: annular relaxed to 0.15 mm (vs upstream 0.25) so that",
        "# legitimate fine-pitch hand-solder headers (J4 LD2410 1.27 mm",
        "# pitch) pass without override. 0.15 mm is still safely above the",
        "# JLCPCB fab-house minimum for 2-layer PTH.",
        '(rule "Pad Size"',
        "\t(constraint hole_size (min 0.5mm))",
        "\t(constraint annular_width (min 0.15mm))",
        "\t(condition \"A.Type == 'Pad' && A.isPlated()\"))",
        "",
        '(rule "Min. Plated Slot Width"',
        "\t(constraint hole_size (min 0.5mm))",
        "\t(condition \"(A.Hole_Size_X != A.Hole_Size_Y) && A.isPlated()\"))",
        "",
        '(rule "Min. Non-Plated Slot Width"',
        "\t(constraint hole_size (min 1.0mm))",
        "\t(condition \"(A.Hole_Size_X != A.Hole_Size_Y) && !A.isPlated()\"))",
        "",
        "# --- Hole-to-hole and pad-to-pad clearances ---",
        '(rule "hole to hole clearance (different nets)"',
        "\t(constraint hole_to_hole (min 0.5mm))",
        "\t(condition \"A.Net != B.Net\"))",
        "",
        '(rule "via to track clearance"',
        "\t(constraint hole_clearance (min 0.254mm))",
        "\t(condition \"A.Type == 'via' && B.Type == 'track'\"))",
        "",
        '(rule "via to via clearance (same nets)"',
        "\t(constraint hole_to_hole (min 0.254mm))",
        "\t(condition \"A.Type == 'via' && B.Type == A.Type && A.Net == B.Net\"))",
        "",
        '(rule "pad to pad clearance (with hole, different nets)"',
        "\t(constraint hole_to_hole (min 0.5mm))",
        "\t(condition \"A.Type == 'pad' && B.Type == A.Type && A.Net != B.Net\"))",
        "",
        '(rule "pad to pad clearance (without hole, different nets)"',
        "\t(constraint clearance (min 0.127mm))",
        "\t(condition \"A.Type == 'Pad' && B.Type == 'Pad'\"))",
        "",
        '(rule "NPTH to Track clearance"',
        "\t(constraint hole_clearance (min 0.254mm))",
        "\t(condition \"A.Pad_Type == 'NPTH, mechanical' && B.Type == 'track'\"))",
        "",
        '(rule "NPTH with copper around"',
        "\t(constraint hole_clearance (min 0.20mm))",
        "\t(condition \"A.Pad_Type == 'NPTH, mechanical' && B.Type != 'track'\"))",
        "",
        '(rule "PTH to Track clearance"',
        "\t(constraint hole_clearance (min 0.33mm))",
        "\t(condition \"A.isPlated() && A.Type != 'Via' && B.Type == 'track'\"))",
        "",
        '(rule "Pad to Track clearance"',
        "\t(constraint clearance (min 0.2mm))",
        "\t(condition \"A.isPlated() && A.Type != 'Via' && B.Type == 'track'\"))",
        "",
        "# --- Board edge clearance (default routed) ---",
        '(rule "Trace to Outline"',
        "\t(constraint edge_clearance (min 0.3mm))",
        "\t(condition \"A.Type == 'track'\"))",
        "",
        "# --- Silkscreen text and pad-to-silk clearance ---",
        '(rule "Minimum Text"',
        "\t(constraint text_thickness (min 0.15mm))",
        "\t(constraint text_height (min 1mm))",
        '\t(layer "?.Silkscreen"))',
        "",
        "# Pad to Silkscreen: 0.10 mm clearance — relaxed from upstream 0.14",
        "# because KiCad standard ceramic-cap footprints (0402/0603/0805)",
        "# place the silk outline 0.10 mm from pad edges by convention.",
        "# JLCPCB accepts this as a DFM warning (not blocker); enforcing",
        "# stricter would force editing every stock-library cap footprint.",
        '(rule "Pad to Silkscreen"',
        "\t(constraint silk_clearance (min 0.10mm))",
        "\t(layer outer)",
        "\t(condition \"A.Type == 'pad' && (B.Type == 'text' || B.Type == 'graphic')\"))",
        "",
    ]
    return "\n".join(rules)
